---
- hosts: ssoro
  gather_facts: no
  tasks:
  - name: CLONE AND CONFIGURE MACHINE
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_name }}"
      template: "{{ template }}"
      #datacenter: "cc-miniserv-05"
      folder: /
      datastore: "{{ vm_datastore }}"
      convert: thin
      networks:
      - name: "{{ vm_network }}"
        ip: "{{ ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        type: static
      state: poweredon
      wait_for_ip_address: yes
      disk:
      - size_gb: "{{ vm_disk01_size }}"
        datastore: "{{ vm_datastore }}"
      hardware:
        memory_mb: "{{ vm_mem_size }}"
        num_cpus: "{{ vm_num_cpus }}"
